### ISSUE TITLE
Inconsistent reference to the substrate-ui repo

### ISSUE THREAD

**Issue by ltfschoen** [shawntabrizi/substrate-collectables-workshop#57]
When referring to the https://github.com/paritytech/substrate-ui repo, we appear to be inconsistently referring to it both as a Substrate UI and a Polkadot UI.

**Comment by shawntabrizi** [comment]
@ltfschoen are you sure?

At most points in the tutorial we are using the "Polkadot UI": https://polkadot.js.org/apps/

Then at the end, in chapter 4, we modify the "Substrate UI", which is the repo you linked to in your post.

It may be that we have accidentally referenced one when we meant to reference the other, but that should be a basic update, just let me know where.

Otherwise, it was intentional that we are using 2 different tools throughout our tutorial.

**Comment by shawntabrizi** [comment]
@ltfschoen if you think there is still an issue feel free to re-open or ping
