### ISSUE TITLE
substrate-node-new creates accounts with 0 balance

### ISSUE THREAD

**Issue by korniii** [shawntabrizi/substrate-collectables-workshop#73]
Hi,

i was trying to go through the substratekitties workshop. Unfortunately when i set up the dev chain with `substrate-node-new substratekitties someName` and then start the node with `cd substratekitties
./target/release/substratekitties --dev` all dummy accounts are created with a balance of 0. Therefore i can't make any transactions / balance transfers.

Is there anything i need to change in some kind of config fil? I am clueless how how to fix this issue. Thanks in advance. :)

btw. I'm working on a Mac.

**Comment by jkcomment** [comment]
I have the same problem.

**Comment by shawntabrizi** [comment]
There were breaking changes that happened with Substrate related to Account Key generation.

See:
https://github.com/paritytech/substrate/pull/1795
https://github.com/polkadot-js/apps/issues/828

This _should_ no longer be an issue since Substrate and Polkadot UI are now in sync, but tell me if that is not the case and I can investigate.
